---
- hosts: dev
  become: True
  tasks:


    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Install docker
      yum:
        name: docker-ce
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: " Starting and Enabling Docker service"
      service:
        name: docker
        state: started
        enabled: yes
    - name: Start the container
      docker_container:
        name: montadeployment
        image: "https://hub.docker.com/montassardev/montadeployment:{{DOCKER_TAG}}"
        state: started
        pull: true
        exposed_ports:
          - 8080:8080
    
    

