---
- hosts: dev
  become: True
  tasks:


    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: "Allow all traffic"
      service:
        name: firewalld
        state: stopped
    - name: "Installing python"
      package:
        name: "python3"
        state: present 
    - name: "Checking python"
      command: "pip3 list | grep docker"
      register: docker_skd
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Install docker
      yum:
        name: docker-ce
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: " Starting and Enabling Docker service"
      service:
        name: docker
        state: started
        enabled: yes
    - name: Start the container
      docker_image:
        name: "montadeployment"
        image: "https://hub.docker.com/montassardev/montadeployment:{{DOCKER_TAG}}"
        state: started
        pull: true
        exposed_ports:
          - 8080:8080
    
    

